version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
    pre_build:
      commands:
        - echo Nothing to do in the pre_build phase...
        - npm test
        - echo '#!/bin/bash' > /usr/local/bin/ok; echo 'if [[ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]]; then exit 1; else exit 0; fi' >> /usr/local/bin/ok; chmod +x /usr/local/bin/ok
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - package.json
    - package-lock.json
    - 'src/**/*'
    - README.md
  name: yourBuildName-$(date +%Y-%m-%d)
